### PR TITLE
Implement load dataset function (Phase 1)

### PR DESCRIPTION
**Pull request by KedoKudo**
This PR introduces the following changes:

- Implement functionality to allow batch loading dataset (data, background and normalization) defined from a Python file (dictionary)
- Add example Python file
- Add corresponding unit tests

To Test
---------

- Clone the feature branch and setup editable install as instructed in Readme.
- Use the load dataset button to load the data definition file from test folder
image
  - since there is only one dataset defined, it will use it by default
  - if there are multiple ones, a pop up window will show up to allow selection
- The data and normalization should be set automatically after click okay
image

> IBM item: [Story592](https://ornlrse.clm.ibmcloud.com/ccm/web/projects/Neutron%20Data%20Project%20(Change%20Management)#action=com.ibm.team.workitem.viewWorkItem&id=592)

### CODE REVIEW

**Comment by KedoKudo** [comment]
> Can you make this more resilient to bad input?
> 
> For example if you don't define `define_data_set` Shiver crashes with
> 
> ```
> Traceback (most recent call last):
>   File "/home/rwp/src/DGS_SC_scripts/src/shiver/views/loading_buttons.py", line 69, in _on_load_dataset_click
>     data_set_list = self.extract_dataset_list(filename)
>   File "/home/rwp/src/DGS_SC_scripts/src/shiver/views/loading_buttons.py", line 118, in extract_dataset_list
>     data_set_list = module.define_data_set()
> AttributeError: module 'define_data' has no attribute 'define_data_set'
> ```
> 
> Or if the dict is missing a required parameter then Shiver crashes with
> 
> ```
> Traceback (most recent call last):
>   File "/home/rwp/src/DGS_SC_scripts/src/shiver/views/loading_buttons.py", line 95, in _on_load_dataset_click
>     self.load_dataset_callback(data_set)
>   File "/home/rwp/src/DGS_SC_scripts/src/shiver/presenters/histogram.py", line 42, in load_dataset
>     data, background, norm = self.model.load_dataset(dataset)
>   File "/home/rwp/src/DGS_SC_scripts/src/shiver/models/histogram.py", line 73, in load_dataset
>     if dataset["MdeName"] is not None:
> KeyError: 'MdeName'
> ```

Requested error handling is added with the latest change.

**Review by rosswhitfield — CHANGES_REQUESTED** [review]
If I load the test `define_data.py` then delete just the MDE, when I reload the `define_data.py` it crashes

```
Traceback (most recent call last):
  File "/home/rwp/src/DGS_SC_scripts/src/shiver/views/loading_buttons.py", line 96, in _on_load_dataset_click
    self.load_dataset_callback(data_set)
  File "/home/rwp/src/DGS_SC_scripts/src/shiver/presenters/histogram.py", line 46, in load_dataset
    self.view.set_data(data)
  File "/home/rwp/src/DGS_SC_scripts/src/shiver/views/histogram.py", line 106, in set_data
    self.input_workspaces.mde_workspaces.set_data(data)
  File "/home/rwp/src/DGS_SC_scripts/src/shiver/views/workspace_tables.py", line 241, in set_data
    item = self.findItems(name, Qt.MatchExactly)[0]
IndexError: list index out of range
```

**Comment by KedoKudo** [comment]
> If I load the test `define_data.py` then delete just the MDE, when I reload the `define_data.py` it crashes
> 
> ```
> Traceback (most recent call last):
>   File "/home/rwp/src/DGS_SC_scripts/src/shiver/views/loading_buttons.py", line 96, in _on_load_dataset_click
>     self.load_dataset_callback(data_set)
>   File "/home/rwp/src/DGS_SC_scripts/src/shiver/presenters/histogram.py", line 46, in load_dataset
>     self.view.set_data(data)
>   File "/home/rwp/src/DGS_SC_scripts/src/shiver/views/histogram.py", line 106, in set_data
>     self.input_workspaces.mde_workspaces.set_data(data)
>   File "/home/rwp/src/DGS_SC_scripts/src/shiver/views/workspace_tables.py", line 241, in set_data
>     item = self.findItems(name, Qt.MatchExactly)[0]
> IndexError: list index out of range
> ```

The suggested solution that helps bypass the async related racing condition (between alg_observer and ads_observer) has been added.

**Review by AndreiSavici — CHANGES_REQUESTED** [review]
The following should be addressed:
1. If there is a syntax error in the python file it causes mantid to pop up the terminate dialog. Not good. To test, just remove the ":" from the function definition. 
2. The first thing to do is to unselect any data/background/normalization. Otherwise the loading can fail, and the data is not set correctly

**Comment by KedoKudo** [comment]
> The following should be addressed:
> 
> 1. If there is a syntax error in the python file it causes mantid to pop up the terminate dialog. Not good. To test, just remove the ":" from the function definition.
> 2. The first thing to do is to unselect any data/background/normalization. Otherwise the loading can fail, and the data is not set correctly

The reported edges are handled with latest changes. Please take another look.

**Review by AndreiSavici — APPROVED** [review]

**Review by rosswhitfield — APPROVED** [review]

**Pull request merged**
