### PR TITLE
Convert to mde

### PR DESCRIPTION
**Pull request by AndreiSavici**
Creates algorithms to convert to MDE

### CODE REVIEW

**Review by mpatrou — COMMENTED** [review]
The fields are filled in as show in the following image:
no_log_screen


After clicking 'Run', the warning message appears on the side: No log values for goniometers . The algorithm is executed in the end, though.

**Review by mpatrou — COMMENTED** [review]
The fields are filled in as shown:
(additional dimensions invalid)
adt_screen

After clicking 'Run', the logs on the side contain this one:
Error in execution of algorithm ConvertToMD:
Unknown property search object x
Error in execution of algorithm ConvertDGSToSingleMDE:
ConvertToMD-v1: Unknown property search object x
  at line 380 in '/home/dwp/Projects/Shiver/src/shiver/models/ConvertDGSToSingleMDE.py'
  caused by line 1077 in '/home/dwp/anaconda3/envs/shiver/lib/python3.8/site-packages/mantid/simpleapi.py'

**Review by mpatrou — COMMENTED** [review]
The fields are:

nexus_screen

The error related to Nexus appears after clicking 'Run':
Error in execution of algorithm LoadNexusProcessed:
Cannot open group mantid_workspace_1 of class NXentry (trying to open path /mantid_workspace_1)
Error in execution of algorithm ConvertDGSToSingleMDE:
LoadNexusProcessed-v2: Cannot open group mantid_workspace_1 of class NXentry (trying to open path /mantid_workspace_1)
  at line 235 in '/home/dwp/Projects/Shiver/src/shiver/models/ConvertDGSToSingleMDE.py'
  caused by line 1077 in '/home/dwp/anaconda3/envs/shiver/lib/python3.8/site-packages/mantid/simpleapi.py'

**Review by mpatrou — COMMENTED** [review]
Fields are filled in as show below:
xmax_screen

The following error appears after clicking 'Run':
Error in execution of algorithm ExtractSpectra:
XMax is less than the smallest X value (5 < 12306)
Error in execution of algorithm CropWorkspace:
XMax is less than the smallest X value (5 < 12306)
Error in execution of algorithm CreateFlatEventWorkspace:
XMax is less than the smallest X value (5 < 12306)
Error in execution of algorithm DgsConvertToEnergyTransfer:
XMax is less than the smallest X value (5 < 12306)
Error in execution of algorithm DgsReduction:
XMax is less than the smallest X value (5 < 12306)
Error in execution of algorithm ConvertDGSToSingleMDE:
XMax is less than the smallest X value (5 < 12306)
  at line 339 in '/home/dwp/Projects/Shiver/src/shiver/models/ConvertDGSToSingleMDE.py'
  caused by line 1070 in '/home/dwp/anaconda3/envs/shiver/lib/python3.8/site-packages/mantid/simpleapi.py'

**Review by mpatrou — COMMENTED** [review]
The fields are filled in as shown below:

seq_screen

The following error appears:
Number of detectors does not match between mask workspace and input workspaceMask is from a different instrument to the input workspace. Error in execution of algorithm MaskDetectors:
_Map_base::at
Error in execution of algorithm ConvertDGSToSingleMDE:
_Map_base::at
  at line 253 in '/home/dwp/Projects/Shiver/src/shiver/models/ConvertDGSToSingleMDE.py'
  caused by line 1070 in '/home/dwp/anaconda3/envs/shiver/lib/python3.8/site-packages/mantid/simpleapi.py'


**UPDATE**
The same error appear with TimeIndependentBackground value = ' ' (space)

**Comment by AndreiSavici** [comment]
> The fields are filled in as show in the following image: no_log_screen
> 
> After clicking 'Run', the warning message appears on the side: No log values for goniometers . The algorithm is executed in the end, though.

That's the correct behavior

**Comment by AndreiSavici** [comment]
> The fields are filled in as shown: (additional dimensions invalid) adt_screen
> 
> After clicking 'Run', the logs on the side contain this one: Error in execution of algorithm ConvertToMD: Unknown property search object x Error in execution of algorithm ConvertDGSToSingleMDE: ConvertToMD-v1: Unknown property search object x at line 380 in '/home/dwp/Projects/Shiver/src/shiver/models/ConvertDGSToSingleMDE.py' caused by line 1077 in '/home/dwp/anaconda3/envs/shiver/lib/python3.8/site-packages/mantid/simpleapi.py'

The behavior is correct, but we might try to catch this thing right after load, using `CheckForSampleLogs`

**Comment by AndreiSavici** [comment]
The rest of the errors are expected: trying to load a raw file when you specified processed one, using time independent background outside limits of the workspace, and using a mask from a different instrument than the given workspace.

**Comment by rosswhitfield** [comment]
@AndreiSavici a lot of those error messages are not user-friendly and could easily be improved.

**Pull request merged**
